"""followers

Revision ID: 124023605f27
Revises: 2d3cc6be5043
Create Date: 2018-04-15 21:31:50.652555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124023605f27'
down_revision = '2d3cc6be5043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
